# Generated by Django 4.1.7 on 2023-03-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='presenca',
            field=models.CharField(max_length=10),
        ),
    ]
